# syntax=docker/dockerfile:experimental
FROM openjdk:8-jdk-alpine as build
WORKDIR /workspace/app

COPY [ "mvnw","pom.xml", "./" ]
COPY .mvn .mvn
COPY src src

RUN --mount=type=cache,target=/root/.m2 ./mvnw install -DskipTests \
&& mkdir -p target/dependency \
&& (cd target/dependency; jar -xf ../*.jar)

FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
CMD ["java","-cp","app:app/lib/*","com.example.todoserviceregistry.TodoServiceRegistryApplication"]